---
repos:
  - repo: git@github.com:Ghostfacts/pre-commit-checks.git
    rev: fe6a4e0860f6d72bee3d2a4be2deafb4c9eee735
    hooks:
      #Code checks
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: "notebooks"
      - id: check-json
        exclude: "terraform/files/website/themes/newsai/layouts/_default/index.json"
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      #IaC checks
      - id: terraform-fmt
      - id: terraform_tflint
      - id: terraform-validate
      #python checks
      - id: pylint
      - id: black
      - id: flake8
      - id: mypy
      - id: isort
      - id: bandit
