repos:
  - repo: git@github.com:Ghostfacts/pre-commit-checks.git
    rev: f834020bc4d40102714908a744a1e3c57fe23aff
    hooks:
      #Code checks
      - id: check-added-large-files
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      #IaC checks
      - id: terraform-fmt
      - id: trailing-whitespace
      #python checks
      - id: pylint
      - id: black
      - id: flake8
      - id: mypy
      - id: isort
      - id: bandit
