---
repos:
  - repo: git@github.com:Ghostfacts/pre-commit-checks.git
    rev: 223b4dd6027df6dda04f9e4ab4b8c7a602f0ffde
    hooks:
      #Code checks
      - id: check-added-large-files
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      #IaC checks
      - id: terraform-fmt
      - id: terraform_tflint
      - id: terraform-validate
      #python checks
      - id: pylint
      - id: black
      - id: flake8
      - id: mypy
      - id: isort
      - id: bandit
