version: 0.2

env:
  variables: {}
  parameter-store: {}

phases:
  install:
    commands:
      - apt-get -qq update && apt-get -qq install curl
      - apt-get -qq install asciidoctor
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_0.145.0_linux-amd64.deb -o hugo.deb
      - dpkg -i hugo.deb
    finally:
      - echo Installation done
  build:
    commands:
      - echo "Pulling website from S3..."
      - aws s3 cp s3://$SOURCE_BUCKET/website/ ./website/ --recursive
      - echo "Running Hugo build..."
      - cd website
      - hugo version
      - hugo --cleanDestinationDir --minify --noBuildLock
    finally:
      - echo Building the HTML files finished
  post_build:
    commands:
      - echo "Uploading published content to S3..."
      - aws s3 cp ./public/ s3://$DESTINATION_BUCKET/ --recursive
      - aws cloudfront create-invalidation --distribution-id $CDNID --paths "/*"
    finally:
      - echo "Build and upload completed"
artifacts:
  files: []
