version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing Hugo..."
      - npm install -g hugo-cli
  build:
    commands:
      - echo "Pulling website from S3..."
      - aws s3 cp s3://$SOURCE_BUCKET/website/ ./website/ --recursive
      - echo "Running Hugo build..."
      - cd website
      - hugo
  post_build:
    commands:
      - echo "Uploading published content to S3..."
      - aws s3 cp ./website/public/ s3://$DESTINATION_BUCKET/ --recursive
