# terrascan configuration file

# scan and skip rules configuration
[rules]
    # skip rules (list of rules to skip)
    skip-rules = [
        "AC_AWS_0215",
        "AC_AWS_0214",
        "AC_AWS_0500",
        "AC_AWS_0012",
        "AWS.AST.DP.MEDIUM.0037",
        "AWS.LambdaFunction.EncryptionandKeyManagement.0471",
        "AWS.LambdaFunction.LM.MEIDUM.0063",

    ]