---
name: Terraform Deploy
permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write
  checks: write
  security-events: write
  issues: write
  

on:
  push:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  terraformdeploy:
    strategy:
      matrix:
        environment:
          - development
    runs-on: ubuntu-latest
    steps:
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
          role-session-name: ${{ github.sha }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform init
        shell: sh
        run: |
          terraform init -input=false -no-color -upgrade -reconfigure -backend-config=config/${{ matrix.environment }}/backend.conf -var-file=config/${{ matrix.environment }}/terraform.tfvars
        working-directory: terraform

      - name: Terraform apply
        shell: sh
        run : |
          terraform apply -var-file=config/${{ matrix.environment }}/terraform.tfvars --auto-approve
        working-directory: terraform
