name: Delete Old Workflow Runs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@v4

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
        with:
          gh-cli-version: 2.65.0 # optional, see action.yml for current default
=======
        uses: actions/checkout@v4.2.2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
>>>>>>> 8e2db21 (Purge workflows)

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
        run: echo "${GITHUB_TOKEN}" | gh auth login --with-token
=======
        run: gh auth login --with-token
>>>>>>> 8e2db21 (Purge workflows)

      - name: Delete old workflow runs
        env:
          REPO: ${{ github.repository }}
        run: |
          # Get the current date in seconds since epoch
          current_date=$(date +%s)

          # Get all workflow runs
<<<<<<< HEAD
          runs=$(gh api "repos/${REPO}/actions/runs" --paginate -q '.workflow_runs[] | select(.event != "workflow_dispatch") | [.id, .created_at]')

          # Loop through each run and delete if older than 30 days
          echo "$runs" | jq -r '. | @tsv' | while IFS=$'\t' read -r id created_at; do
=======
          runs=$(gh api repos/${REPO}/actions/runs --paginate -q '.workflow_runs[] | select(.event != "workflow_dispatch") | [.id, .created_at]')

          # Loop through each run and delete if older than 30 days
          echo "$runs" | while read -r id created_at; do
>>>>>>> 8e2db21 (Purge workflows)
            created_at_seconds=$(date -d "$created_at" +%s)
            age=$(( (current_date - created_at_seconds) / 86400 ))
            if [ "$age" -gt 30 ]; then
              echo "Deleting run $id ($created_at, $age days old)"
<<<<<<< HEAD
              gh api "repos/${REPO}/actions/runs/$id" -X DELETE
            fi
          done
=======
              gh api repos/${REPO}/actions/runs/$id -X DELETE
            fi
          done
>>>>>>> 8e2db21 (Purge workflows)
